config/routes.rb
Rails.application.routes.draw do
	root 'items#index'

	resources :feeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
	has_many :items, dependent: :destroy

	validates_presence_of :name, :url
	validates_uniqueness_of :url

	# NOTE: Very basic url format checker
	validates_format_of :url, with: URI::regexp(%w(http https))
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :feed

	validates_presence_of :title, :url, :published_date
	validates_uniqueness_of :url, :title

	# NOTE: Very basic url format checker
	validates_format_of :url, with: URI::regexp(%w(http https))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

	before_action :set_feed!, except: :index

	def index
		@feeds = Feed.all
	end

	def create
	  @feed = Feed.new(feed_params)

    if @feed.save
    	redirect_to feeds_url, notice: 'Feed was successfully created.'
    else
      render :new, error: 'Failed! to create feed.'
    end
	end

	def update
  	if @feed.update_attributes(feed_params)
  		redirect_to feed_url(@feed), notice: 'Feed was successfully updated.'
  	else
  	  render :new, error: 'Failed! to updated feed.'
  	end
	end

	def destroy
	  if @feed.destroy
	  	redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
	  else
	  	render feeds_path, error: "Unable to destroy feed #{@feed.name}"
	  end
	end

	private
  def set_feed!
    @feed = Feed.find(params[:id]) rescue Feed.new
  end

  def feed_params
    params.require(:feed).permit(:name, :url)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all.order('published_date desc')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(key)
		case key
			when 'notice' then 'alert alert-success'
			when 'error' then 'alert alert-danger'
		end
	end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/feeds/_form.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@feed.errors.count, 'error') %> please fix the below errors:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='form-group col-xs-6 col-sm-4'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class='row'>
    <div class='form-group col-xs-6 col-sm-4'>
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.submit  class: 'btn btn-primary btn-small', style: 'color: white' %>
  </div>

<% end %>

app/views/feeds/edit.erb
<%= content_for :title, '| Edit' %>

<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path, class: 'btn btn-primary btn-small', style: "color: white" %>

app/views/feeds/index.erb
<%= content_for :title, '| List' %>

<p id="notice"><%= notice %></p>

<h1>Listing Feeds</h1>
<div class="table-responsive">
  <table class="table table-sm table-striped table-bordered">
     <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= link_to 'Show', feed, class: 'btn btn-primary btn-xs'%></td>
        <td><%= link_to 'Edit', edit_feed_path(feed), class: 'btn btn-success btn-xs' %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Feed', new_feed_path, class: 'btn btn-primary btn-small', style: "color: white" %>

app/views/feeds/new.erb
<%= content_for :title, '| Create' %>

<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path, class: 'btn btn-primary btn-small', style: "color: white" %>

app/views/feeds/show.erb
<%= content_for :title, '| view' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/items/index.erb
<div class='container'>
  <% @items.each do |item| %>
    <div class='panel panel-default'>
      <div class='panel-body'>
        <%= link_to item.title, item.url, target: :_blank %> - <i> published <%= time_ago_in_words(item.published_date) %> ago.</i>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Rss Feed #{yield(:title)}" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/components/header' %>

    <div class='container'>
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>" role='alert'>
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/components/_header.erb
<nav class='navbar navbar-inverse'>
  <div class='container'>
    <div class='navbar-header'>
      <%= link_to 'RSS Feed', root_path, class: 'navbar-brand' %>
    </div>
    <div id='navbar'>
      <ul class='nav navbar-nav'>
        <li><%= link_to 'Manage Feed', feeds_path %></li>
      </ul>
    </div>
  </div>
</nav>